# Generated by Django 5.0.1 on 2024-02-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='displa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Displa Name')),
                ('year', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('material', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
            ],
        ),
    ]
